/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare class Agent {
  static create(config: AgentConfig): Promise<Agent>
  static createWithBus(config: AgentConfig, bus: ExternalObject<Session>): Promise<Agent>
  runSimple(task: string): Promise<string>
  react(task: string): Promise<string>
  config(): any
  listTools(): Array<string>
  registerHook(event: HookEvent, callback: ((err: Error | null, arg: HookContextData) => any)): void
  registerPlugin(name: string, onLlmRequest?: (((err: Error | null, arg: JSAny) => any)) | undefined | null, onLlmResponse?: (((err: Error | null, arg: JSAny) => any)) | undefined | null, onToolCall?: (((err: Error | null, arg: JSAny) => any)) | undefined | null, onToolResult?: (((err: Error | null, arg: JSAny) => any)) | undefined | null): void
  close(): void
  addTool(name: string, description: string, parameters: string, schema: string, callback: ((err: Error | null, arg: JSAny) => any)): Promise<string>
  addBashTool(name: string, workspaceRoot?: string | undefined | null): Promise<void>
  registerSkillsFromDir(dirPath: string): Promise<void>
  addMcpServer(namespace: string, command: string, args: Array<string>): Promise<void>
  addMcpServerHttp(namespace: string, url: string): Promise<void>
  listMcpTools(): Promise<Array<any>>
  listMcpResources(namespace: string): Promise<Array<any>>
  listMcpPrompts(): Promise<Array<any>>
  rpcClient(endpoint: string, bus: ExternalObject<Session>): Promise<AgentRpcClient>
  asCallableServer(endpoint: string, bus: ExternalObject<Session>): Promise<AgentCallableServer>
  addMessage(message: any): Promise<void>
  getMessages(): Array<any>
  saveMessageLog(path: string): void
  restoreMessageLog(path: string): void
  stream(task: string, callback: ((err: Error | null, arg: any) => any)): Promise<void>
}

export declare class AgentCallableServer {
  get endpoint(): string
  isStarted(): boolean
}

export declare class AgentRpcClient {
  get endpoint(): string
  list(): Promise<any>
  call(toolName: string, argsJson: string): Promise<any>
  llmRun(task: string): Promise<any>
}

export declare class Bus {
  static create(config?: BusConfig | undefined | null): Promise<Bus>
  session(): Promise<ExternalObject<Session>>
  sessionId(): string
  publishText(topic: string, payload: string): Promise<void>
  publishJson(topic: string, data: any): Promise<void>
  createPublisher(topic: string): Promise<Publisher>
  createSubscriber(topic: string): Promise<Subscriber>
  createQuery(topic: string): Promise<Query>
  createQueryable(topic: string): Promise<Queryable>
  createCaller(name: string): Promise<Caller>
  createCallable(uri: string): Promise<Callable>
}

export declare class Callable {
  setHandler(handler: ((err: Error | null, arg: string) => unknown)): void
  isStarted(): boolean
  start(): Promise<void>
  run(handler: ((err: Error | null, arg: string) => unknown)): Promise<void>
  runJson(handler: ((err: Error | null, arg: string) => unknown)): Promise<void>
}

export declare class Caller {
  static new(name: string): Promise<Caller>
  static withSession(name: string, session: ExternalObject<Session>): Promise<Caller>
  callText(payload: string): Promise<string>
}

export declare class ConfigLoader {
  constructor()
  discover(): void
  addFile(path: string): void
  addDirectory(path: string): void
  addInline(data: any): void
  reset(): void
  loadSync(): string
  reloadSync(): string
}

export declare class HookRegistry {
  constructor()
  register(event: HookEvent, callback: ((err: Error | null, arg: HookContextData) => any)): Promise<void>
}

export declare class McpClient {
  static spawn(command: string, args: Array<string>): Promise<McpClient>
  static connectHttp(url: string): McpClient
  initialize(): Promise<any>
  listTools(): Promise<Array<any>>
  callTool(name: string, argsJson: string): Promise<any>
  listPrompts(): Promise<Array<any>>
  listResources(): Promise<Array<any>>
  readResource(uri: string): Promise<any>
}

export declare class PluginRegistry {
  constructor()
  clear(): Promise<void>
}

export declare class Publisher {
  static new(topic: string): Promise<Publisher>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Publisher>
  get topic(): string
  publishText(payload: string): Promise<void>
  publishJson(data: any): Promise<void>
}

export declare class Query {
  static new(topic: string): Promise<Query>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Query>
  get topic(): string
  queryText(payload: string): Promise<string>
  queryTextTimeoutMs(payload: string, timeoutMs: number): Promise<string>
}

export declare class Queryable {
  static new(topic: string): Promise<Queryable>
  setHandler(handler: ((err: Error | null, arg: string) => unknown)): void
  start(): Promise<void>
  run(handler: ((err: Error | null, arg: string) => unknown)): Promise<void>
  runJson(handler: ((err: Error | null, arg: string) => unknown)): Promise<void>
  runStream(handler: ((err: Error | null, arg: string) => unknown)): Promise<void>
}

export declare class Subscriber {
  static new(topic: string): Promise<Subscriber>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Subscriber>
  get topic(): string
  recv(): Promise<string | null>
  recvWithTimeoutMs(timeoutMs: number): Promise<string | null>
  recvJsonWithTimeoutMs(timeoutMs: number): Promise<any | null>
  run(handler: ((err: Error | null, arg: JSAny) => any)): Promise<void>
  runJson(handler: ((err: Error | null, arg: JSAny) => any)): Promise<void>
  stop(): Promise<void>
}

export interface AgentConfig {
  name: string
  model: string
  baseUrl: string
  apiKey: string
  systemPrompt: string
  temperature: number
  maxTokens?: number
  timeoutSecs: number
  maxSteps?: number
  circuitBreakerMaxFailures?: number
  circuitBreakerCooldownSecs?: number
  rateLimitCapacity?: number
  rateLimitWindowSecs?: number
  rateLimitMaxRetries?: number
  rateLimitRetryBackoffSecs?: number
  rateLimitAutoWait?: boolean
  contextCompactionThresholdTokens?: number
  contextCompactionTriggerRatio?: number
  contextCompactionKeepRecentMessages?: number
  contextCompactionMaxSummaryChars?: number
  contextCompactionSummaryMaxTokens?: number
}

export interface BusConfig {
  mode: string
  connect?: Array<string>
  listen?: Array<string>
  peer?: string
}

export interface HookContextData {
  agentId: string
  data: Record<string, string>
}

export declare const enum HookDecision {
  Continue = 0,
  Abort = 1,
  Error = 2
}

export declare const enum HookEvent {
  BeforeToolCall = 0,
  AfterToolCall = 1,
  BeforeLlmCall = 2,
  AfterLlmCall = 3,
  OnMessage = 4,
  OnComplete = 5,
  OnError = 6
}

export declare function initTracing(): void

export declare function logTestMessage(message: string): void

export interface PluginLlmRequest {
  model: string
  temperature?: number
  maxTokens?: number
  topP?: number
  topK?: number
  metadata: Record<string, string>
}

export type PluginLlmResponse =
  | { type: 'Text', field0: string }
  | { type: 'Partial', field0: string }
  | { type: 'ToolCall', name: string, args: string, id?: string }
  | { type: 'Done' }

export declare const enum PluginStage {
  PreRequest = 0,
  PostResponse = 1,
  PreExecute = 2,
  PostExecute = 3
}

export interface PluginToolCall {
  name: string
  args: string
  id?: string
  metadata: Record<string, string>
}

export interface PluginToolResult {
  result: string
  success: boolean
  error?: string
  metadata: Record<string, string>
}

export declare function version(): string
