/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface AgentConfig {
  name: string
  model: string
  baseUrl: string
  apiKey: string
  systemPrompt: string
  temperature: number
  maxTokens?: number
  timeoutSecs: number
  maxSteps?: number
  contextCompactionThresholdTokens?: number
  contextCompactionTriggerRatio?: number
  contextCompactionKeepRecentMessages?: number
  contextCompactionMaxSummaryChars?: number
  contextCompactionSummaryMaxTokens?: number
}
export interface BusConfig {
  mode: string
  connect?: Array<string>
  listen?: Array<string>
  peer?: string
}
export declare function version(): string
export declare class Agent {
  static create(config: AgentConfig): Promise<Agent>
  static createWithBus(config: AgentConfig, bus: ExternalObject<Session>): Promise<Agent>
  runSimple(task: string): Promise<string>
  react(task: string): Promise<string>
  config(): any
  listTools(): Array<string>
  addTool(name: string, description: string, parameters: string, schema: string, callback: (err: Error | null, arg: JSAny) => any): Promise<string>
  registerSkillsFromDir(dirPath: string): Promise<void>
  addMcpServer(namespace: string, command: string, args: Array<string>): Promise<void>
  addMcpServerHttp(namespace: string, url: string): Promise<void>
  listMcpTools(): Promise<Array<any>>
  listMcpResources(namespace: string): Promise<Array<any>>
  listMcpPrompts(): Promise<Array<any>>
  rpcClient(endpoint: string, bus: ExternalObject<Session>): Promise<AgentRpcClient>
  asCallableServer(endpoint: string, bus: ExternalObject<Session>): Promise<AgentCallableServer>
}
export declare class AgentRpcClient {
  get endpoint(): string
  list(): Promise<any>
  call(toolName: string, argsJson: string): Promise<any>
  llmRun(task: string): Promise<any>
}
export declare class AgentCallableServer {
  get endpoint(): string
  isStarted(): boolean
}
export declare class Bus {
  static create(config?: BusConfig | undefined | null): Promise<Bus>
  session(): Promise<ExternalObject<Session>>
  sessionId(): string
  publishText(topic: string, payload: string): Promise<void>
  publishJson(topic: string, data: any): Promise<void>
  createPublisher(topic: string): Promise<Publisher>
  createSubscriber(topic: string): Promise<Subscriber>
  createQuery(topic: string): Promise<Query>
  createQueryable(topic: string): Promise<Queryable>
  createCaller(name: string): Promise<Caller>
  createCallable(uri: string): Promise<Callable>
}
export declare class Caller {
  static new(name: string): Promise<Caller>
  static withSession(name: string, session: ExternalObject<Session>): Promise<Caller>
  callText(payload: string): Promise<string>
}
export declare class Callable {
  setHandler(handler: (err: Error | null, arg: string) => any): void
  isStarted(): boolean
  start(): Promise<void>
  run(handler: (err: Error | null, arg: string) => any): Promise<void>
  runJson(handler: (err: Error | null, arg: string) => any): Promise<void>
}
export declare class ConfigLoader {
  constructor()
  discover(): void
  addFile(path: string): void
  addDirectory(path: string): void
  addInline(data: any): void
  reset(): void
  loadSync(): string
  reloadSync(): string
}
export declare class McpClient {
  static spawn(command: string, args: Array<string>): Promise<McpClient>
  static connectHttp(url: string): McpClient
  initialize(): Promise<any>
  listTools(): Promise<Array<any>>
  callTool(name: string, argsJson: string): Promise<any>
  listPrompts(): Promise<Array<any>>
  listResources(): Promise<Array<any>>
  readResource(uri: string): Promise<any>
}
export declare class Publisher {
  static new(topic: string): Promise<Publisher>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Publisher>
  get topic(): string
  publishText(payload: string): Promise<void>
  publishJson(data: any): Promise<void>
}
export declare class Query {
  static new(topic: string): Promise<Query>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Query>
  get topic(): string
  queryText(payload: string): Promise<string>
  queryTextTimeoutMs(payload: string, timeoutMs: number): Promise<string>
}
export declare class Queryable {
  static new(topic: string): Promise<Queryable>
  setHandler(handler: (err: Error | null, arg: string) => any): void
  start(): Promise<void>
  run(handler: (err: Error | null, arg: string) => any): Promise<void>
  runJson(handler: (err: Error | null, arg: string) => any): Promise<void>
  runStream(handler: (err: Error | null, arg: string) => any): Promise<void>
}
export declare class Subscriber {
  static new(topic: string): Promise<Subscriber>
  static withSession(topic: string, session: ExternalObject<Session>): Promise<Subscriber>
  get topic(): string
  recv(): Promise<string | null>
  recvWithTimeoutMs(timeoutMs: number): Promise<string | null>
  recvJsonWithTimeoutMs(timeoutMs: number): Promise<any | null>
  run(handler: (err: Error | null, arg: JSAny) => any): Promise<void>
  runJson(handler: (err: Error | null, arg: JSAny) => any): Promise<void>
  stop(): Promise<void>
}
