[package]
name = "bsh"
description = "BOS Harness, Native desktop built on Tauri"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tauri = { version = "2", features = [] }
agent = { path = "../agent" }
async-trait = { workspace = true }
config = { path = "../config" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
async-channel = { workspace = true }
uuid = { workspace = true }
shellexpand = { workspace = true }
toml = { workspace = true }
portable-pty = "0.9"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "bshlib"
path = "src/lib.rs"

[[bin]]
name = "bsh"
path = "src/main.rs"
