#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { tmpdir } from 'os'

const __dirname = dirname(fileURLToPath(import.meta.url))

const rootDir = join(__dirname, '..')
const tmpOutDir = join(tmpdir(), 'jsbos-dts')
const jsbosDts = readFileSync(join(rootDir, 'jsbos.d.ts'), 'utf8')

execSync(
  `npx tsc index.js --declaration --allowJs --emitDeclarationOnly --outDir "${tmpOutDir}" --skipLibCheck --ignoreConfig 2>/dev/null || true`,
  { cwd: rootDir }
)

let indexDts = ''
try {
  indexDts = readFileSync(join(tmpOutDir, 'index.d.ts'), 'utf8')
} catch {
  console.warn('tsc failed to generate index.d.ts')
  process.exit(1)
}

let merged = `/* Low-level native bindings (NAPI-RS auto-generated) */\n`
merged += jsbosDts.replace(/^\/\* auto-generated by NAPI-RS \*\/\n/, '').replace(/^\/\* eslint-disable \*\/\n/, '').trim() + '\n\n'
merged += `/* High-level API types (tsc auto-generated from index.js) */\n`
merged += indexDts.trim()

writeFileSync(join(rootDir, 'index.d.ts'), merged, 'utf8')
console.log('index.d.ts generated')
