name: Performance

on:
  schedule:
    - cron: '0 0 * * *'  # 每天
  workflow_dispatch:

jobs:
  full-perf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gnuplot

      - name: Run full benchmark
        run: |
          cargo bench | tee full.txt

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nightly-perf
          path: |
            full.txt
            target/criterion